{{ $imageTag := or ($.Values.image.tag) (.Chart.AppVersion) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fuzzball.fullname" . }}
  labels:
    {{- include "fuzzball.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "fuzzball.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "fuzzball.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "fuzzball.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ $imageTag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: MONGO_URI
          value: {{ include "fuzzball.mongoURI" . }}
        - name: NATS_URIS
          value: {{ include "fuzzball.natsURI" . }}
        {{- if .Values.oAuth2.audience }}
        - name: OAUTH2_AUDIENCE
          value: {{ .Values.oAuth2.audience }}
        {{- end }}
        {{- if .Values.oAuth2.issuerURI }}
        - name: OAUTH2_ISSUER_URI
          value: {{ .Values.oAuth2.issuerURI }}
        {{- end }}
        - name: REDIS_URI
          value: {{ include "fuzzball.redisURI" . }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
